name: Server - ESLint and Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  eslint-tests:
    name: Run ESLint and Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: ${{secrets.USER}}
          POSTGRES_PASSWORD: ${{secrets.PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        id: checkout-repository
        uses: actions/checkout@v4

      - name: Install pnpm
        id: install-pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Configure node
        id: configure-node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Create .env.test file
        id: create-env-test-file
        run: echo "${{ secrets.ENV_TEST_FILE }}" > .env.test

      - name: Install dependencies
        id: install-dependencies
        working-directory: ./server
        run: pnpm install

      - name: Check ESLint
        id: check-eslint
        working-directory: ./server
        run: pnpm run lint

      - name: Run tests
        id: run-tests
        working-directory: ./server
        run: pnpm run ci:test
